[package]
name = "rust_ble_sandbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
btleplug = "^0.9.0"
tokio = { version = "^1.10.0", features = ["full"] }
futures = "^0.3.16"
