[package]
name = "dmc_vigem_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
websocket = "0.24.0"
serde_json="1.0"
vigem-client = "0.1"
dmc = { path = "../dmc" }
