[package]
name = "mmap_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap = "~0.7.0"
serde = { version = "~1.0.133", features = ["derive"] }
bincode = "~1.3.3"
